import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

type User = {
  id: number;
  name: string;
  username: string;
  email: string;
  address: string;
  phone: string;
  website: object;
  company: object;
};

export default function Home({ data }: { data: User[] }) {
  const items = data.map((item) => (
    <div
      style={{
        width: "200px",
        height: "200px",
        border: "1px solid black",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
      key={item.id.toString()}
    >
      {item.name}
    </div>
  ));

  return (
    <div>
      <Head>
        <title>Felipe Muner - Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="json-placeholder">
          {items}
          {items}
        </div>
        {/* <div className="json-placeholder">felipe</div>
        <div className="json-placeholder">felipe</div> */}
        <div className="main">
          <div className="shadow-in"></div>
          <div className="shadow-two"></div>
          <div className="shadow-three"></div>
        </div>
        <style jsx>{`
          .json-placeholder {
            height: 100vh;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
          }
          .main {
            height: 100vh;
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
          }
          .shadow-in {
            margin-right: 5vh;
            background-color: #fff;
            width: 200px;
            height: 200px;
            -moz-box-shadow: inset 0 0 10px #000000;
            -webkit-box-shadow: inset 0 0 10px #000000;
            box-shadow: inset 0 0 10px #000000;
          }
          .shadow-two {
            margin-right: 5vh;
            background-color: white;
            width: 200px;
            height: 200px;
            box-shadow: rgb(204, 219, 232) 3px 3px 6px 0px inset,
              rgba(255, 255, 255, 0.5) -3px -3px 6px 1px inset;
          }
          .shadow-three {
            width: 200px;
            height: 200px;
            box-shadow: rgb(38, 57, 77) 0px 20px 30px -10px;
          }
        `}</style>
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data: User = await res.json();
  console.log(data);

  return {
    props: {
      data,
    },
  };
};
