import Head from "next/head";
import SkeletonGrid from "../components/SkeletonGrid";
import { useEffect, useState } from "react";
// import Skeleton from "@material-ui/lab/Skeleton";

type User = {
  id: number;
  name: string;
  username: string;
  email: string;
  address: string;
  phone: string;
  website: object;
  company: object;
};

// export default function Home({ data }: { data: User[] }) {
export default function Home() {
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [users, setUsers] = useState<User[]>([]);

  const getUsers = async () => {
    const res = await fetch("https://jsonplaceholder.typicode.com/users");
    const data: User[] = await res.json();
    setUsers(data);
    setIsLoading(false);
  };

  useEffect(() => {
    setTimeout(() => {
      getUsers();
    }, 2000);
  }, []);

  const items = users.map((item) => (
    <div
      style={{
        boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
        width: "300px",
        height: "300px",
        backgroundColor: "white",
        margin: "15px",
        padding: "15px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
      key={item.id.toString()}
    >
      {item.name}
    </div>
  ));

  if (isLoading)
    return <SkeletonGrid />;

  return (
    <div>
      <Head>
        <title>Felipe Muner - Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="json-placeholder">
          {items}
          {items}
        </div>
        <style jsx>{`
          .json-placeholder {
            height: 100vh;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            margin-top: 50px;
          }
        `}</style>
      </div>
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const res = await fetch("https://jsonplaceholder.typicode.com/users");
//   const data: User = await res.json();
//   console.log(data);

//   return {
//     props: {
//       data,
//     },
//   };
// };
