import { GetServerSideProps } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

type User = {
  id: number;
  name: string;
  username: string;
  email: string;
  address: string;
  phone: string;
  website: object;
  company: object;
};

export default function Home({ data }: { data: User[] }) {
  // const items = data.map((item) => (
  //   <div
  //     className="card"
  //     style={{
  //       width: "300px",
  //       height: "300px",
  //       border: "1px solid white",
  //       backgroundColor: "white",
  //       margin: "15px",
  //       display: "flex",
  //       alignItems: "center",
  //       justifyContent: "center",
  //     }}
  //     key={item.id.toString()}
  //   >
  //     {item.name}
  //   </div>
  // ));

  return (
    <div>
      <Head>
        <title>Felipe Muner - Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div
          style={{
            display: "flex",
            textAlign:"center",
            justifyContent: "center",
            alignContent:"center",
            flexWrap: "wrap",
            marginTop: "50px",
          }}
        >
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
          <div className="skeleton-div"></div>
        </div>
        <style jsx>{`
          .skeleton-div {
            background-image: linear-gradient(
              90deg,
              #ddd 25%,
              #eee 37%,
              #ddd 63%
            );
            width: 300px;
            height: 300px;
            margin: 15px;
            list-style: none;
            background-size: 400% 100%;
            // background-position: 100% 50%;
            animation: skeleton-loading 2s ease infinite;
          }

          @keyframes skeleton-loading {
            0% {
              background-position: 100% 50%;
            }
            100% {
              background-position: 0 50%;
            }
          }
        `}</style>
      </div>
    </div>
  );
}

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const res = await fetch("https://jsonplaceholder.typicode.com/users");
//   const data: User = await res.json();
//   console.log(data);

//   return {
//     props: {
//       data,
//     },
//   };
// };
